QuoteWeb/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Modelos.Quote;
using Persistencia;
using QuoteWeb.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace QuoteWeb.Controllers
{
    public class ClienteController : Controller
    {
        private readonly QuoteDB db;

        public ClienteController(QuoteDB db)
        {
            this.db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Cliente> ListaClientes = db.clientes;
            return View(ListaClientes);
        }


        // POST
        //  Guarda un nuevo cliente

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Cliente cliente)
        {
            db.clientes.Add(cliente);
            db.SaveChanges();

            TempData["mensaje"] = $"el cliente {cliente.Nombre} se ha creado correctamente";

            return RedirectToAction("Index");
        }

        // Presenta el formulario con la identidad seleccionada para actualizar
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Cliente cliente = db.clientes.Find(id);

            return View(cliente);
        }

        [HttpPost]
        public IActionResult Edit(Cliente cliente)
        {
            db.clientes.Update(cliente);
            db.SaveChanges();

            TempData["mensaje"] = $"La materia {cliente.Nombre} se ha actualizado correctamente";

            return RedirectToAction("Index");
        }


        // Presenta el formulario con la identidad seleccionada para borrar
        [HttpGet]
        public IActionResult Delete(int id)
        {
            Cliente cliente = db.clientes.Find(id);

            return View(cliente);
        }

        [HttpPost]
        public IActionResult Delete(Cliente cliente)
        {
            db.clientes.Remove(cliente);
            db.SaveChanges();

            TempData["mensaje"] = $"El cliente {cliente.Nombre} se ha borrado correctamente";

            return RedirectToAction("Index");
        }


    }
}

QuoteWeb/Controllers/KitController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Modelos.Quote;
using Persistencia;
using QuoteWeb.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace QuoteWeb.Controllers
{
    public class KitController : Controller
    {
        private readonly QuoteDB db;

        public KitController(QuoteDB db)
        {
            this.db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Kit> ListaKit = 
                db.kits
                 .Include(ListaKit => ListaKit.KitParts);
            
            return View(ListaKit);
        }


        // POST
        //  Guarda un nuevo cliente

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Kit kit)
        {
            db.kits.Add(kit);
            db.SaveChanges();

            TempData["mensaje"] = $"el kit {kit.KitId} se ha creado correctamente";

            return RedirectToAction("Index");
        }

        // Presenta el formulario con la identidad seleccionada para actualizar
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Kit kit = db.kits.Find(id);

            return View(kit);
        }

        [HttpPost]
        public IActionResult Edit(Kit kit)
        {
            db.kits.Update(kit);
            db.SaveChanges();

            TempData["mensaje"] = $"el kit {kit.Nombre} se ha actualizado correctamente";

            return RedirectToAction("Index");
        }


        // Presenta el formulario con la identidad seleccionada para borrar
        [HttpGet]
        public IActionResult Delete(int id)
        {
            Kit kit = db.kits.Find(id);

            return View(kit);
        }

        [HttpPost]
        public IActionResult Delete(Kit kit)
        {
            db.kits.Remove(kit);
            db.SaveChanges();

            TempData["mensaje"] = $"el kit {kit.Nombre} se ha borrado correctamente";

            return RedirectToAction("Index");
        }


    }
}

QuoteWeb/Controllers/ParteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Modelos.Quote;
using Persistencia;
using QuoteWeb.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace QuoteWeb.Controllers
{
    public class ParteController : Controller
    {
        private readonly QuoteDB db;

        public ParteController(QuoteDB db)
        {
            this.db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Parte> ListaParte = db.partes;
            
            return View(ListaParte);
        }


        // POST
        //  Guarda un nuevo cliente

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Parte parte)
        {
            db.partes.Add(parte);
            db.SaveChanges();

            TempData["mensaje"] = $"la proforma {parte.ParteId} se ha creado correctamente";

            return RedirectToAction("Index");
        }

        // Presenta el formulario con la identidad seleccionada para actualizar
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Parte parte = db.partes.Find(id);

            return View(parte);
        }

        [HttpPost]
        public IActionResult Edit(Parte parte)
        {
            db.partes.Update(parte);
            db.SaveChanges();

            TempData["mensaje"] = $"La parte  {parte.Nombre} se ha actualizado correctamente";

            return RedirectToAction("Index");
        }


        // Presenta el formulario con la identidad seleccionada para borrar
        [HttpGet]
        public IActionResult Delete(int id)
        {
            Parte parte = db.partes.Find(id);

            return View(parte);
        }

        [HttpPost]
        public IActionResult Delete(Parte parte)
        {
            db.partes.Remove(parte);
            db.SaveChanges();

            TempData["mensaje"] = $"la parte {parte.Nombre} se ha borrado correctamente";

            return RedirectToAction("Index");
        }


    }
}

QuoteWeb/Controllers/QuoteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Modelos.Quote;
using Persistencia;
using QuoteWeb.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace QuoteWeb.Controllers
{
    public class QuoteController : Controller
    {
        private readonly QuoteDB db;

        public QuoteController(QuoteDB db)
        {
            this.db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Quote> ListaQuote =
             db.quotes
            .Include(quote => quote.Cliente)
            .Include(quote => quote.Estado)
            .Include(quote => quote.kit);
          /*  .Include(quote => quote.Cliente)
            .Include(quote => quote.kit)
            .ThenInclude(qKit => qKit.KitParts)
            .ThenInclude(qKitParts => qKitParts.Parte);
        */
            return View(ListaQuote);
        }


        // POST
        //  Guarda un nuevo cliente

        [HttpGet]
        public IActionResult Create()
        {
            //lista de clientes
            var listaClientes = db.clientes
                .Select(cliente => new
                {
                    ClienteId = cliente.ClienteId,
                    Nombre = cliente.Nombre
                }).ToList();

            //lista de kits
            var kits = db.kits
                .Select(kit => new
                {
                    KitId = kit.KitId,
                    Nombre = kit.Nombre
                }).ToList();

            //lista de estados
            var listaEstados = db.estados
                .Select(estado => new
                {
                    EstadoId = estado.EstadoId,
                    EstadoValor = estado.EstadoValor
                }).ToList();

            //preparas las listas
            var selectListasClientes = new SelectList(listaClientes, "ClienteId", "Nombre");
            var selectListasKit = new SelectList(kits, "KitId", "Nombre");
            var selectListasEstados = new SelectList(listaEstados, "EstadoId", "EstadoValor");

            ViewBag.selectListasClientes = selectListasClientes;
            ViewBag.selectListasKit = selectListasKit;
            ViewBag.selectListasEstados = selectListasEstados;

            return View();
        }

        [HttpPost]
        public IActionResult Create(Quote quote)
        {
            db.quotes.Add(quote);
            db.SaveChanges();

            TempData["mensaje"] = $"la proforma {quote.QuoteId} se ha creado correctamente";

            return RedirectToAction("Index");
        }

        // Presenta el formulario con la identidad seleccionada para actualizar
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Cliente cliente = db.clientes.Find(id);

            return View(cliente);
        }

        [HttpPost]
        public IActionResult Edit(Cliente cliente)
        {
            db.clientes.Update(cliente);
            db.SaveChanges();

            TempData["mensaje"] = $"La materia {cliente.Nombre} se ha actualizado correctamente";

            return RedirectToAction("Index");
        }


        // Presenta el formulario con la identidad seleccionada para borrar
        [HttpGet]
        public IActionResult Delete(int id)
        {
            Cliente cliente = db.clientes.Find(id);

            return View(cliente);
        }

        [HttpPost]
        public IActionResult Delete(Cliente cliente)
        {
            db.clientes.Remove(cliente);
            db.SaveChanges();

            TempData["mensaje"] = $"El cliente {cliente.Nombre} se ha borrado correctamente";

            return RedirectToAction("Index");
        }


    }
}

QuoteWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QuoteWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">QuoteWeb</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a>
                        </li>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Quote" asp-action="Index">Quotes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Parte" asp-action="Index">Partes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AltParte" asp-action="Index">Partes alternas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Kit" asp-action="Index">Kits</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - QuoteWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>