QuoteWeb/Controllers/AltParteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Modelos.Quote;
using Persistencia;
using QuoteWeb.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace QuoteWeb.Controllers
{
    public class AltParteController : Controller
    {
        private readonly QuoteDB db;

        public AltParteController(QuoteDB db)
        {
            this.db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<AltParte> ListaAltParte = db.altPartes
                 .Include(altparte => altparte.Parte);
            
            return View(ListaAltParte);
        }


        // POST
        //  Guarda un nuevo cliente

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(AltParte altparte)
        {
            db.altPartes.Add(altparte);
            db.SaveChanges();

            TempData["mensaje"] = $"la parte aletrna {altparte.ParteAlternaId} se ha creado correctamente";

            return RedirectToAction("Index");
        }

        // Presenta el formulario con la identidad seleccionada para actualizar
        [HttpGet]
        public IActionResult Edit(int id)
        {
            AltParte altparte = db.altPartes.Find(id);

            return View(altparte);
        }

        [HttpPost]
        public IActionResult Edit(AltParte altparte)
        {
            db.altPartes.Update(altparte);
            db.SaveChanges();

            TempData["mensaje"] = $"La parte  {altparte.ParteAlternaId} se ha actualizado correctamente";

            return RedirectToAction("Index");
        }


        // Presenta el formulario con la identidad seleccionada para borrar
        [HttpGet]
        public IActionResult Delete(int id)
        {
            AltParte altparte = db.altPartes.Find(id);

            return View(altparte);
        }

        [HttpPost]
        public IActionResult Delete(AltParte altparte)
        {
            db.altPartes.Remove(altparte);
            db.SaveChanges();

            TempData["mensaje"] = $"la parte {altparte.ParteAlternaId} se ha borrado correctamente";

            return RedirectToAction("Index");
        }


    }
}

QuoteWeb/Views/AltParte/Create.cshtml
@using Modelos.Quote
@model AltParte
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

QuoteWeb/Views/AltParte/Index.cshtml
@using Modelos.Quote
@model IEnumerable<AltParte>
    @{
        ViewData["Title"] = "Index";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }

    <h1>Partes Alternas</h1>
    <p>Se presenta las partes alternas de la proforma</p>

    <div class="container">
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            @TempData["mensaje"]
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <h3>Lista de partes alternas</h3>
            </div>


            <div class="col-sm-6">
                <a class="btn btn-success d-block" asp-controller="AltParte" asp-action="Create">
                    Crear una parte alterna
                </a>
            </div>
        </div>
        <div class="row">
            @if (Model.Count() > 0)
            {
                <table class=" table table-bordered table-striped">
                    <thead>
                        <tr>
                            <td>Id Parte</td>
                            <td>Nombre Parte</td>
                            <td>Id parte alterna</td>
                            <td>Nombre parte alterna</td>
                            <td>Stock parte alterna</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (AltParte altparte in Model)
                        {
                        <tr>
                            <td>@altparte.ParteId</td>
                            <td>@altparte.Parte.Nombre</td>
                            <td>@altparte.ParteAlternaId</td>
                            <td>@altparte.ParteAlterna.Nombre</td>
                            <td>@altparte.ParteAlterna.Stock</td>



                            <td>
                                <center>
                                    <a class="btn btn-warning"
                                       asp-controller="AltParte" asp-action="Edit" asp-route-id="@altparte.ParteAlternaId">
                                        Editar
                                    </a>
                                    <a class="btn btn-danger"
                                       asp-controller="AltParte" asp-action="Delete" asp-route-id="@altparte.ParteAlternaId">
                                        Borrar
                                    </a>
                                </center>
                            </td>
                        </tr>
                        }

                    </tbody>
                </table>
            }
            <div class="col-sm-6">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Salir</a>
                </a>
            </div>
        </div>
    </div>